### ISSUE TITLE
Inline resources to the HTML?

### ISSUE THREAD

**Issue by jamen** [soundcove/app-client#10]
I'd like to know the thoughts and progress on inlining the resources into the HTML.  I would like this to be decided and done before I persue #9, otherwise I'm going to have to redo things afterwards.

**Comment by jamen** [comment]
@soundcove/front-end-devs

**Comment by whaaaley** [comment]
You can go ahead an create a deploy script for just `index.html`, the logic to that script won't change depending on it's contents. The app-server can't do anything but serve the index file anyway right? This will have to be completed before we launch do to that reason alone.

**Comment by jamen** [comment]
I would still like this to be done first, just in case.  It's also weird for me to create a non-working deploy script right now.  I would basically like to create it when it will work.

**Comment by whaaaley** [comment]
This is complete so you can move forward on #9
