### ISSUE TITLE
Convert from gulp to vue files

### ISSUE THREAD

**Issue by whaaaley** [soundcove/app-client#14]
...with Vueify and drop Pug/Jade and Bower in the process.

**Comment by seanc** [comment]
do you want ownership of this org

**Comment by JunosX** [comment]
Sure

On Dec 23, 2016 2:07 PM, "Sean Wilson [Masked]"
<FWD-737QTYSMENAIYCQANIQDDYCOEEGCYMCTACTBDQDWEFGTAAUJIB3AQIIZWNF4STIAAHVVTHAB2NYS4EOGCVSAGQBAVBICCMWWGE4EC5I7EIOKIAFMAVBTL4Y2IJGOAWXXKO5ARRCXBAACKIKBEARVAJYYERMCCOBALASTWQC5MAHYAC4AAXXH6AAL5IACWIBGLIUUBIQKYQFFQEBAAAQA====@
opayq.com> wrote:

**Comment by whaaaley** [comment]
@seanc Yes

**Comment by JelaniThompson** [comment]
Is this still being worked on?

**Comment by jamen** [comment]
Dunno

**Comment by vectrixdevelops** [comment]
I smell progress? Assistance needed?

**Comment by whaaaley** [comment]
i made some things here because i was bored, that's all

**Comment by seanc** [comment]
turns out you're already owner, so :+1:
